/**
 * Service Agreement visit tracking, shared by the Service Agreements page,
 * the Customer Portal (server/customerPortal.ts) and the recurring
 * scheduler. Pure functions only -- no React, no Firestore -- so the server
 * can import this file too.
 *
 * A visit for an agreement is either:
 *  - a Work Order with sourceMembershipId (auto-generated by the server's
 *    recurring scheduler, or created from a Work Order form), or
 *  - a Job with sourceMembershipId (booked from Service Agreements >
 *    Schedule Visit).
 * A Work Order's companion calendar entry (sourceWorkOrderId) is the same
 * visit, never a second one.
 *
 * "Visits left" is always derived from completed visits, never stored, so
 * re-saving or re-completing something can't count a visit twice. Only
 * visits dated on/after the agreement's current startDate count toward it,
 * so a renewal starts a fresh term while earlier visits stay in history.
 */

export interface AgreementLike {
  id: string;
  status?: string;
  visitsIncluded?: number;
  nextMaintenanceDate?: string;
  startDate?: string;
  endDate?: string;
  previousStartDate?: string;
}

export interface WorkOrderLike {
  id: string;
  sourceMembershipId?: string;
  status?: string;
  date?: string;
  scheduledDate?: string;
}

export interface EventLike {
  id: string;
  eventType?: string;
  sourceMembershipId?: string;
  sourceWorkOrderId?: string;
  status?: string;
  date?: string;
}

export interface AgreementVisit {
  /** Work Order id or Job id. */
  id: string;
  kind: "work_order" | "job";
  date: string;
  completed: boolean;
}

export interface AgreementVisitStats {
  /** Every visit ever linked to the agreement, all terms. */
  visits: AgreementVisit[];
  /** Completed visits in the current term. */
  completedCount: number;
  /** null when the agreement has no visit limit. */
  remaining: number | null;
  /** Earliest open (not completed/cancelled) visit, if one is booked. */
  openVisit?: AgreementVisit;
  /** The open visit's date, otherwise the next date the scheduler will generate one. */
  nextVisitDate?: string;
}

const isCancelled = (status?: string) => status === "Cancelled" || status === "Canceled";

export function agreementVisits(agreementId: string, workOrders: WorkOrderLike[], events: EventLike[]): AgreementVisit[] {
  const visits: AgreementVisit[] = [];
  const workOrderIds = new Set<string>();
  for (const wo of workOrders) {
    if (wo.sourceMembershipId !== agreementId || isCancelled(wo.status)) continue;
    workOrderIds.add(wo.id);
    // A Work Order's companion calendar entry can be marked Completed from
    // Scheduling/Dispatch without touching the Work Order itself -- either
    // one being Completed means the visit happened.
    const companionCompleted = events.some(e => e.sourceWorkOrderId === wo.id && e.status === "Completed");
    visits.push({ id: wo.id, kind: "work_order", date: wo.scheduledDate || wo.date || "", completed: wo.status === "Completed" || companionCompleted });
  }
  for (const e of events) {
    if (e.eventType !== "Job" || e.sourceMembershipId !== agreementId || isCancelled(e.status)) continue;
    if (e.sourceWorkOrderId && workOrderIds.has(e.sourceWorkOrderId)) continue;
    visits.push({ id: e.id, kind: "job", date: e.date || "", completed: e.status === "Completed" });
  }
  return visits.sort((a, b) => a.date.localeCompare(b.date));
}

export function agreementVisitStats(agreement: AgreementLike, workOrders: WorkOrderLike[], events: EventLike[], today = new Date().toISOString().slice(0, 10)): AgreementVisitStats {
  const visits = agreementVisits(agreement.id, workOrders, events);
  // Renewed early: the new term hasn't started yet, so keep counting the current one.
  const termStart = agreement.startDate && agreement.startDate > today && agreement.previousStartDate
    ? agreement.previousStartDate
    : agreement.startDate;
  const inTerm = (v: AgreementVisit) => !termStart || !v.date || v.date >= termStart;
  const completedCount = visits.filter(v => v.completed && inTerm(v)).length;
  const remaining = typeof agreement.visitsIncluded === "number" && agreement.visitsIncluded > 0
    ? Math.max(0, agreement.visitsIncluded - completedCount)
    : null;
  const openVisit = visits.find(v => !v.completed);
  const active = agreement.status === "Active";
  const nextVisitDate = openVisit?.date || (active && remaining !== 0 ? agreement.nextMaintenanceDate : undefined) || undefined;
  return { visits, completedCount, remaining, openVisit, nextVisitDate };
}

export function addDaysIso(date: string, days: number): string {
  const d = new Date(`${date}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

/** Next visit is overdue or within `days` days. */
export function isVisitDueSoon(nextVisitDate: string | undefined, today: string, days = 30): boolean {
  return !!nextVisitDate && nextVisitDate <= addDaysIso(today, days);
}

/** Active agreement ending within `days` days (and not already past). */
export function isAgreementExpiringSoon(agreement: AgreementLike, today: string, days = 30): boolean {
  return agreement.status === "Active" && !!agreement.endDate && agreement.endDate >= today && agreement.endDate <= addDaysIso(today, days);
}
